name: "sonar_cloud_scan_github_actions"

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
 DomeSonarCloudScan:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
       with: 
            fetch-depth: 0
     - name: SonarCloud Scan
       uses: sonarsource/sonarcloud-github-action@master
       env: 
           GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}  
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       with:
          args: >
             -Dsonar.projectKey=Sonar-Qube
             -Dsonar.organization=kazimabusnaimeh
