name: SonarQube analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read 

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'

      - name: Install SonarScanner
        run: |
         SONAR_SCANNER_VERSION=$(curl -s https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/ | grep -o 'sonar-scanner-cli-[0-9.]\+-linux.zip' | sort -V | tail -n 1)
         curl -LsS "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/$SONAR_SCANNER_VERSION" -o sonar-scanner.zip
         unzip sonar-scanner.zip
         mv sonar-scanner-cli-* /opt/sonar-scanner
         echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH


      - name: Verify Java Version
        run: java -version

      - name: Run SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          /opt/sonar-scanner/bin/sonar-scanner \
            -Dsonar.projectKey="sonarqude" \
            -Dsonar.projectName="sonarqude" \
            -Dsonar.token="${{ secrets.SONAR_TOKEN }}" \
            -Dsonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
            -Dsonar.language="kotlin" \
            -Dsonar.sourceEncoding="UTF-8" \
            -Dsonar.sources="src/main/"
