name: SonarQube analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Java 17 as default
        run: echo "JAVA_HOME=$(which java)" >> $GITHUB_ENV

      - name: Verify Java Version
        run: java -version

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  
          JAVA_HOME: ${{ env.JAVA_HOME }}   # Ensure SonarQube uses Java 17
        with:
          args:
            -Dsonar.projectKey="sonarqude"
            -Dsonar.projectName="sonarqude"
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} 
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.language="kotlin"
            -Dsonar.sourceEncoding="UTF-8"
            -Dsonar.sources="src/main/"
